use todolist;

insert into task(id, description, is_done, is_deleted) values
(1, 'Viết README mô tả kiến trúc dự án To-Do-List', 0, 0),
(2, 'Tạo API GET /api/task bằng FastAPI', 1, 0),
(3, 'Thiết kế bảng task trong MySQL (DDL, DML)', 0, 0),
(4, 'Cấu hình CORS cho frontend React', 1, 0),
(5, 'Viết unit test cho TaskService', 0, 0),
(6, 'Tối ưu câu lệnh SELECT với LIMIT/OFFSET', 1, 0),
(7, 'Thêm cột is_deleted và cập nhật repository', 0, 0),
(8, 'Tạo Dockerfile cho backend FastAPI', 1, 0),
(9, 'Viết docker-compose để nối web và db', 0, 0),
(10, 'Sửa lỗi kết nối MySQL trong container', 1, 1),
(11, 'Tạo component React hiển thị bảng công việc', 0, 0),
(12, 'Thêm ô tìm kiếm task theo description', 1, 0),
(13, 'Ràng buộc dữ liệu đầu vào với Pydantic', 0, 0),
(14, 'Viết API DELETE cập nhật is_deleted=true', 1, 0),
(15, 'Thêm nút Delete mỗi dòng trong bảng', 0, 0),
(16, 'Căn thẳng hàng cột Done? với checkbox', 1, 0),
(17, 'Tối ưu setState sau khi gọi API', 0, 0),
(18, 'Xử lý lỗi JSON.parse khi response rỗng', 1, 0),
(19, 'Thêm thông báo toast khi tạo/sửa/xóa', 0, 0),
(20, 'Ghi log request/response bằng middleware', 1, 1),
(21, 'Viết hướng dẫn cài đặt dự án trên Windows', 0, 0),
(22, 'Thiết lập .env chứa thông tin DB', 1, 0),
(23, 'Tách lớp DBConnect theo mô hình Singleton', 0, 0),
(24, 'Tạo index cho cột description để search', 1, 0),
(25, 'Chuẩn hóa tên API theo RESTful', 0, 0),
(26, 'Thêm trang phân trang (pagination) cho list', 1, 0),
(27, 'Viết test tích hợp cho API /api/task', 0, 0),
(28, 'Thêm kiểm thử E2E với Playwright', 1, 0),
(29, 'Bảo vệ API bằng API key đơn giản', 0, 0),
(30, 'Cấu hình Nginx reverse proxy cho backend', 1, 1),
(31, 'Tối ưu Docker image (multi-stage build)', 0, 0),
(32, 'Viết script seed dữ liệu mẫu vào MySQL', 1, 0),
(33, 'Thêm trạng thái loading cho bảng React', 0, 0),
(34, 'Hiển thị badge màu cho Done/Pending', 1, 0),
(35, 'Thêm sort theo mô tả và trạng thái', 0, 0),
(36, 'Thiết kế giao diện tối (dark mode) đơn giản', 1, 0),
(37, 'Cập nhật tài liệu API bằng OpenAPI docs', 0, 0),
(38, 'Bổ sung handle lỗi 404/422/500', 1, 0),
(39, 'Gắn nhãn phiên bản v1 cho các route', 0, 0),
(40, 'Tạo healthcheck endpoint /health', 1, 1),
(41, 'Thêm retry kết nối DB khi khởi động', 0, 0),
(42, 'Viết hướng dẫn deploy lên VPS', 1, 0),
(43, 'Cấu hình GitHub Actions CI basic', 0, 0),
(44, 'Thêm badge build status vào README', 1, 0),
(45, 'Kiểm tra bảo mật phụ thuộc (pip audit)', 0, 0),
(46, 'Tối ưu truy vấn LIKE với wildcard phải', 1, 0),
(47, 'Gộp các hàm fetch thành service chung', 0, 0),
(48, 'Chuẩn hóa phản hồi API (code, message, data)', 1, 0),
(49, 'Viết migration script khi đổi schema', 0, 0),
(50, 'Cấu hình backup định kỳ MySQL', 1, 1),
(51, 'Thêm rate limit cho các API công khai', 0, 0),
(52, 'Tối ưu bundle React bằng code-splitting', 1, 0),
(53, 'Bổ sung ESLint/Prettier cho frontend', 0, 0),
(54, 'Tạo hooks useTasks cho logic dùng lại', 1, 0),
(55, 'Tối ưu render bảng bằng memoization', 0, 0),
(56, 'Thử nghiệm React Query cho dữ liệu', 1, 0),
(57, 'Viết tài liệu CONTRIBUTING.md', 0, 0),
(58, 'Tạo ISSUE_TEMPLATE trên GitHub', 1, 0),
(59, 'Chuẩn hóa commit message theo Conventional', 0, 0),
(60, 'Thêm CHANGELOG.md và semantic versioning', 1, 1),
(61, 'Hỗ trợ lọc nhiều điều kiện khi search', 0, 0),
(62, 'Thêm export CSV danh sách công việc', 1, 0),
(63, 'Viết script import từ CSV vào MySQL', 0, 0),
(64, 'Tối ưu chỉ số hiệu năng Lighthouse', 1, 0),
(65, 'Bổ sung thông báo khi không có dữ liệu', 0, 0),
(66, 'Xử lý lỗi mạng và hiển thị retry button', 1, 0),
(67, 'Tạo trang 404 cho frontend', 0, 0),
(68, 'Thêm breadcrumb điều hướng', 1, 0),
(69, 'Đổi favicon và meta tags SEO cơ bản', 0, 0),
(70, 'Tạo trang About mô tả dự án', 1, 1),
(71, 'Viết bài blog ngắn về kiến trúc dự án', 0, 0),
(72, 'Soạn slide giới thiệu To-Do-List demo', 1, 0),
(73, 'Thêm kiểm thử tải nhẹ với k6', 0, 0),
(74, 'Đo thời gian phản hồi API (metrics)', 1, 0),
(75, 'Gắn request ID để theo dõi log', 0, 0),
(76, 'Ẩn thông tin nhạy cảm khỏi log', 1, 0),
(77, 'Thêm trạng thái rỗng (empty state) đẹp', 0, 0),
(78, 'Tối ưu thời gian build Docker', 1, 0),
(79, 'Tạo script khởi tạo network Docker', 0, 0),
(80, 'Kiểm tra kết nối giữa container và db', 1, 1),
(81, 'Học lại khái niệm Redis và RedisInsight', 0, 0),
(82, 'Thử cache simple cho list tasks', 1, 0),
(83, 'Viết note về SOLID trong service layer', 0, 0),
(84, 'Soạn tài liệu phân hệ CRUD theo microservice', 1, 0),
(85, 'Thêm demo WebSocket thông báo real-time', 0, 0),
(86, 'Tối ưu bảo mật CORS theo domain cụ thể', 1, 0),
(87, 'Thử triển khai trên Railway/Render', 0, 0),
(88, 'Tạo script reset database cho dev', 1, 0),
(89, 'Kiểm tra tính tương thích Python 3.12', 0, 0),
(90, 'Sửa cảnh báo Pydantic/Starlette phiên bản', 1, 1),
(91, 'Ôn tập Divide & Conquer: Merge Sort', 0, 0),
(92, 'Implement Strassen nhân ma trận', 1, 0),
(93, 'Viết pseudocode median of medians', 0, 0),
(94, 'Giải bài toán rotten apples bằng BFS', 1, 0),
(95, 'Tóm tắt Sermon on the Mount (Mt 5–7)', 0, 0),
(96, 'Dịch đoạn Free and Easy Wandering (Trang Tử)', 1, 0),
(97, 'Viết dàn ý so sánh Laüstic và một truyện Việt', 0, 0),
(98, 'Ghi chú về Đạo Đức Kinh – chương 1', 1, 0),
(99, 'Chuẩn bị literature review về sexuality trong 1001 đêm', 0, 0),
(100, 'Rà soát tài liệu tham khảo theo AMA 11th', 1, 1);
